apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
   name: development-app-of-apps
   namespace: argo-cd
spec:
   project: default
   source:
     repoURL: https://github.com/JacobAmar/argo-cd-preview.git
     targetRevision: HEAD
     path: helm
   destination:
    server: https://kubernetes.default.svc
   syncPolicy:
      automated:
        prune: true
        selfHeal: true