apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
   name: argo-cd-hello-world-chart
   namespace: argo-cd
spec:
   project: default
   source:
     repoURL: https://github.com/JacobAmar/argo-cd-hello-world-chart.git
     targetRevision: HEAD
     path: helm
   destination:
    server: https://kubernetes.default.svc
    namespace: development
   syncPolicy:
      automated:
        prune: true
        selfHeal: true